[workspace]
publish = false
git_release_enable = false

git_tag_enable = true

[[package]]
name = "redactify-core"
changelog_update = true
version_group = "redactify"

[[package]]
name = "redactify-cli"
changelog_update = true
version_group = "redactify"

[[package]]
name = "app"
changelog_update = true
version_group = "redactify"
