name: Assert Branch Naming Convention
run-name: Validate Branch Name Structure

on:
  push:
    branches-ignore:
      - main

jobs:
  check-branch-name:
    name: Enforce Naming Policy
    runs-on: ubuntu-latest
    steps:
      - name: Verify Regex Match
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: '^(feature|bugfix|hotfix|refactor|chore|docs)\/[a-z0-9-]+$'
          ignore: main
